---
- name: Upload files to shared hosting
  hosts: localhost
  connection: local
  vars:
    local_file: "/Users/jeremy/Herd/public.zip"
    remote_dir: "/domains/drmorchcrafts.co.ke/public_html/"
    sftp_host: "102.218.215.123"
    sftp_user: "drmorch1"
    sftp_pass: "qTeN!83Oh8J@f0"  # Replace with your actual password

  tasks:
    - name: Upload file using lftp
      ansible.builtin.command: |
        lftp -e "
        set sftp:connect-program 'ssh -a -x -p 22';
        open sftp://{{ sftp_user }}:{{ sftp_pass }}@{{ sftp_host }};
        cd {{ remote_dir }};
        put {{ local_file }};
        bye"
      no_log: true  # comment
