name: Deploy to Lightsail

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
  DEPLOY_USER: bitnami
  PROJECT_DIR: /opt/bitnami/apache/htdocs/shoe-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via git pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd $PROJECT_DIR
            git pull origin main
            /opt/bitnami/php/bin/php /opt/bitnami/php/bin/composer install --no-dev --optimize-autoloader
            sudo chown -R daemon:daemon storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            sudo /opt/bitnami/ctlscript.sh restart apache
