name: Deploy Laravel App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml
          coverage: none

      - name: Create Laravel directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p storage/app/public
          touch database/database.sqlite
          chmod -R 777 storage bootstrap/cache database

      - name: Configure environment
        run: |
          cp .env.example .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/home/runner/work/shoe-app/shoe-app/database/database.sqlite" >> .env
          php artisan key:generate

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction
          npm ci --no-audit
          npm run build

      - name: Clear caches safely
        run: |
          php artisan cache:clear --no-interaction
          php artisan config:clear
          php artisan view:clear

      - name: Prepare deployment
        run: |
          rm -rf node_modules/ .git/ .github/ tests/ database.sqlite
          rm -f .env

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            .env
            .git/
            .github/
            node_modules/
            tests/
            *.md
            database/
