name: Deploy Laravel App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml

      - name: Create Laravel cache directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p storage/app/public
          chmod -R 777 storage bootstrap/cache

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction
          npm ci --no-audit
          npm run build

      - name: Fix PSR-4 autoloading
        run: |
          composer dump-autoload
          php artisan clear-compiled
          php artisan optimize:clear

      - name: Prepare deployment
        run: |
          rm -rf node_modules/ .git/ .github/ tests/
          cp .env.example .env
          php artisan key:generate

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            .env
            .git/
            .github/
            node_modules/
            tests/
            *.md
