name: Deploy to Lightsail

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  LIGHTSAIL_INSTANCE_IP: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DEPLOY_USER: ubuntu  # or 'ec2-user' for Amazon Linux
  PROJECT_DIR: /opt/bitnami/apache/htdocs/shoe-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          ssh lightsail "sudo apt-get update && sudo apt-get install -y git unzip"

      - name: Deploy application
        run: |
          # Create directory structure
          ssh lightsail "sudo mkdir -p $PROJECT_DIR && sudo chown -R $DEPLOY_USER:$DEPLOY_USER $PROJECT_DIR"

          # Rsync files
          rsync -avz -e "ssh -i ~/.ssh/lightsail_key" \
            --exclude='.git' \
            --exclude='.env' \
            --exclude='storage' \
            ./ ubuntu@$LIGHTSAIL_INSTANCE_IP:$PROJECT_DIR/

          # Install PHP dependencies
          ssh lightsail "cd $PROJECT_DIR && composer install --no-dev --optimize-autoloader"

          # Set up environment
          ssh lightsail "cd $PROJECT_DIR && cp .env.example .env && php artisan key:generate"

          # Set permissions
          ssh lightsail "sudo chown -R www-data:www-data $PROJECT_DIR/storage"
          ssh lightsail "sudo chmod -R 775 $PROJECT_DIR/storage"

          # Restart services
          ssh lightsail "sudo systemctl restart php8.2-fpm nginx"

      - name: Verify deployment
        run: |
          ssh lightsail "curl -I http://localhost"
