name: Deploy Laravel App to Lightsail

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive Laravel project
        run: |
          zip -r shoe-app.zip . -x "vendor/*" "node_modules/*" ".git/*" ".env"

      - name: Upload zip to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "shoe-app.zip"
          target: "/home/bitnami/"

      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            APP_DIR=/opt/bitnami/apache/htdocs/shoe-app
            TMP_DIR=/home/bitnami/shoe-app-temp

            sudo rm -rf /opt/bitnami/apache/htdocs/shoe-app-backup
            sudo mv $APP_DIR /opt/bitnami/apache/htdocs/shoe-app-backup || true
            mkdir -p $APP_DIR

            rm -rf $TMP_DIR
            mkdir -p $TMP_DIR
            unzip -o /home/bitnami/shoe-app.zip -d $TMP_DIR

            # Remove .env from unzipped folder just in case
            rm -f $TMP_DIR/.env

            rsync -av $TMP_DIR/ $APP_DIR/

            cd $APP_DIR

            mkdir -p storage/framework/{cache,sessions,views}
            mkdir -p bootstrap/cache

            sudo chown -R daemon:daemon storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            sudo COMPOSER_ALLOW_SUPERUSER=1 /opt/bitnami/php/bin/composer install --no-dev --optimize-autoloader

            /opt/bitnami/php/bin/php artisan config:clear
            /opt/bitnami/php/bin/php artisan config:cache

            sudo /opt/bitnami/ctlscript.sh restart apache
