name: Deploy Laravel App to Shared Hosting via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml

      - name: Install Composer dependencies (no dev)
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Build frontend assets
        run: |
          npm ci --no-audit
          npm run build

      - name: Prepare project
        run: |
          php artisan config:clear
          php artisan view:clear
          rm -rf .git .github node_modules tests .env vendor

      - name: Upload files to FTP server (excluding vendor folder)
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          server-dir: /home/drmorch1/domains/drmorchcrafts.co.ke/
          local-dir: ./
          exclude: |
            **/vendor/**
            **/.env
            **/.git*
            **/node_modules/**
            **/tests/**
            **/*.md
            database/**
