name: Deploy Laravel App to Shared Hosting via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip project contents (excluding unnecessary files)
        run: |
          zip -r app.zip . -x \
            "vendor/**" \
            "public/**" \
            "node_modules/**" \
            ".git/**" \
            ".github/**" \
            "tests/**" \
            "*.md" \
            "database/**" \
            ".env"

      - name: Unzip contents to a directory for FTP
        run: |
          mkdir upload
          unzip app.zip -d upload

      - name: Upload zipped contents via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "102.218.215.123"
          username: "drmorch1"
          password: "qTeN!83Oh8J@f0"
          protocol: ftp
          port: 21
          server-dir: home/drmorch1/domains/drmorchcrafts.co.ke/
