name: Deploy to Lightsail

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod  # 👈 This is the key

    steps:
      - name: Deploy via git pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LIGHTSAIL_INSTANCE_IP }}
          username: bitnami
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/bitnami/apache/htdocs/shoe-app
            git pull origin main

            # Run composer install as root without prompt
            sudo COMPOSER_ALLOW_SUPERUSER=1 /opt/bitnami/php/bin/composer install --no-dev --optimize-autoloader

            # Clear and cache config
            /opt/bitnami/php/bin/php artisan config:clear
            /opt/bitnami/php/bin/php artisan config:cache

            # Permissions
            sudo chown -R daemon:daemon storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            # Restart apache
            sudo /opt/bitnami/ctlscript.sh restart apache

