name: Deploy Shoe App to Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip project contents (excluding unnecessary files)
        run: |
          zip -r app.zip . -x \
            "vendor/**" \
            "public/**" \
            "node_modules/**" \
            ".git/**" \
            ".github/**" \
            "tests/**" \
            "*.md" \
            "database/**" \
            ".env"

      - name: Upload zipped contents via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{secrets.FTP_HOST}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /domains/drmorchcrafts.co.ke/

      - name: Move assets to public_html directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            mkdir -p /domains/drmorchcrafts.co.ke/public_html/build/assets
            cp -r /domains/drmorchcrafts.co.ke/public/build/assets/* /domains/drmorchcrafts.co.ke/public_html/build/assets/
            echo "Assets moved successfully"
