name: Deploy Laravel App to Shared Hosting via FTP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod  # Matches your secrets environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, ctype, fileinfo, openssl, pdo, tokenizer, xml

      - name: Create Laravel directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/{cache,sessions,views}
          chmod -R 777 storage bootstrap/cache

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction
          npm ci --no-audit
          npm run build

      - name: Clear caches safely
        run: |
          php artisan config:clear
          php artisan view:clear
          rm -f bootstrap/cache/*.php
          rm -rf storage/framework/cache/*

      - name: Prepare deployment
        run: |
          rm -rf node_modules/ .git/ .github/ tests/
          rm -f .env

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}  # Matches your secret name
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            .env
            .git/
            .github/
            node_modules/
            tests/
            *.md
            database/
          server-ftp-timeout: 300
          ftp-sync: true
