name: Deploy Laravel App to Shared Hosting via FTP

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ensure Laravel cache directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/{cache,sessions,views}

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node dependencies and build assets
        run: |
          npm install
          npm run build

      - name: Remove unnecessary files
        run: |
          rm -rf node_modules
          rm -rf .git
          rm -f .env
          rm -f shoe-app.zip

      - name: Archive project
        run: zip -r shoe-app.zip . -x "vendor/*"

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}  # e.g., 102.218.215.123:21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./  # Adjust as needed
          server-dir: /public_html/shoe-app/  # Adjust target directory
