name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, dom, fileinfo
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ensure Laravel cache directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/{cache,sessions,views}

      - name: Install PHP dependencies
        run: composer install --no-progress --no-suggest

      - name: Install Node dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: PHP syntax check
        run: find app -name "*.php" -print0 | xargs -0 -n1 php -l

      - name: Run Laravel tests (if available)
        run: |
          if [ -f artisan ]; then
            php artisan test || echo "No tests found."
          fi
